# Generated by Django 5.0.1 on 2024-02-18 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inscription", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupeParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du groupe")),
                (
                    "date_creation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("VALIDE", "Valide"),
                            ("CREATION", "En cours de création"),
                            ("ECHEC", "Échec"),
                        ],
                        default="CREATION",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "inscripteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscripteur_groupe",
                        to="inscription.inscripteur",
                        verbose_name="Inscripteur",
                    ),
                ),
                (
                    "referent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_administres",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Référent",
                    ),
                ),
            ],
            options={
                "verbose_name": "groupe de participants",
                "verbose_name_plural": "groupes de participants",
                "db_table": "GroupeParticipant",
            },
        ),
        migrations.CreateModel(
            name="ParticipantEstDansGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ajout", models.DateField(auto_now_add=True)),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="intranet.groupeparticipant",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appartenances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "appartenance de groupe",
                "verbose_name_plural": "appartenances de groupe",
                "db_table": "Participant_EstDansGroupe",
            },
        ),
        migrations.AddIndex(
            model_name="groupeparticipant",
            index=models.Index(
                fields=["referent", "nom"], name="GroupeParti_referen_405865_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupeparticipant",
            unique_together={("referent", "nom")},
        ),
        migrations.AlterUniqueTogether(
            name="participantestdansgroupe",
            unique_together={("utilisateur", "groupe")},
        ),
    ]
