# Generated by Django 5.0.1 on 2024-02-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0003_inscripteurexterne_inscriptionexterne_and_more"),
        ("intranet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupeparticipant",
            name="inscripteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscripteur_groupe",
                to="inscription.inscripteurexterne",
                verbose_name="Inscripteur",
            ),
        ),
    ]
