# Generated by Django 5.0.3 on 2024-03-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_inscriptionexterne_nombre_participants_demandes'),
        ('intranet', '0002_alter_groupeparticipant_inscripteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupeparticipant',
            name='inscripteur',
        ),
        migrations.AddField(
            model_name='groupeparticipant',
            name='inscription_externe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscription_externe_groupe', to='inscription.inscriptionexterne', verbose_name='Inscription externe du groupe'),
        ),
    ]
