# Generated by Django 5.0 on 2024-01-01 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreePar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateField()),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilisateurs_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "UserCreePar",
            },
        ),
        migrations.CreateModel(
            name="Epreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("duree", models.IntegerField()),
                ("exercices_un_par_un", models.BooleanField(default=False)),
                ("soumissions_max_par_exercices", models.IntegerField()),
                ("temps_limite", models.BooleanField(default=False)),
                ("presence_flag", models.BooleanField(default=False)),
                ("code_a_soumettre", models.BooleanField(default=False)),
                (
                    "referent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="epreuve_referent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Epreuve",
            },
        ),
        migrations.CreateModel(
            name="GroupeParticipeAEpreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            options={
                "db_table": "GroupeParticipeAEpreuve",
            },
        ),
        migrations.AddField(
            model_name="epreuve",
            name="groupes_participants",
            field=models.ManyToManyField(
                related_name="epreuves",
                through="epreuve.GroupeParticipeAEpreuve",
                to="auth.group",
            ),
        ),
        migrations.CreateModel(
            name="MembreComite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "MembreComite",
            },
        ),
        migrations.AddField(
            model_name="epreuve",
            name="comite",
            field=models.ManyToManyField(
                related_name="epreuves_comite",
                through="epreuve.MembreComite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
