# Generated by Django 5.0.1 on 2024-02-12 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inscription_domaine",
        ),
    ]
