# Generated by Django 5.0.2 on 2024-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuve",
            name="code_unique",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
