# Generated by Django 5.0.1 on 2024-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0003_delete_inscription_domaine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epreuve",
            name="date_debut",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="date_fin",
            field=models.DateTimeField(),
        ),
    ]
