# Generated by Django 5.0 on 2024-01-02 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("epreuve", "0003_epreuve_date_fin_apres_date_debut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="epreuve",
            name="date_fin_apres_date_debut",
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="date_debut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="epreuve",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("date_debut__isnull", True),
                        ("date_fin__isnull", True),
                        ("date_fin__gte", models.F("date_debut")),
                        _connector="OR",
                    )
                ),
                name="date_fin_apres_ou_egale_a_date_debut_si_non_null",
            ),
        ),
    ]
