# Generated by Django 5.0.2 on 2024-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0003_epreuve_code_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epreuve",
            name="code_unique",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
