# Generated by Django 5.0 on 2024-01-08 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0004_remove_epreuve_date_fin_apres_date_debut_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epreuve",
            name="code_a_soumettre",
        ),
        migrations.RemoveField(
            model_name="epreuve",
            name="presence_flag",
        ),
        migrations.RemoveField(
            model_name="epreuve",
            name="soumissions_max_par_exercices",
        ),
    ]
