# Generated by Django 5.0.2 on 2024-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0004_alter_epreuve_code_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="epreuve",
            old_name="code_unique",
            new_name="code",
        ),
    ]
