# Generated by Django 5.0 on 2024-01-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0005_remove_epreuve_code_a_soumettre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupecreepar",
            name="nombre_participants",
            field=models.IntegerField(default=0),
        ),
    ]
