# Generated by Django 5.0.3 on 2024-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuve', '0005_rename_code_unique_epreuve_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userepreuve',
            name='debut_epreuve',
            field=models.DateTimeField(null=True),
        ),
    ]
