# Generated by Django 5.0 on 2024-01-10 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("epreuve", "0006_groupecreepar_nombre_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="epreuve",
            index=models.Index(fields=["referent"], name="Epreuve_referen_cb6879_idx"),
        ),
        migrations.AddIndex(
            model_name="groupecreepar",
            index=models.Index(
                fields=["createur"], name="GroupeCreeP_createu_819c01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupeparticipeaepreuve",
            index=models.Index(
                fields=["groupe", "epreuve"], name="GroupeParti_groupe__c70cd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membrecomite",
            index=models.Index(
                fields=["epreuve", "membre"], name="MembreComit_epreuve_8e0baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercreepar",
            index=models.Index(
                fields=["createur"], name="UserCreePar_createu_18c368_idx"
            ),
        ),
    ]
