# Generated by Django 5.0.3 on 2024-03-19 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0006_userepreuve_debut_epreuve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userepreuve",
            name="fin_epreuve",
        ),
    ]
