# Generated by Django 5.0 on 2024-01-10 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("epreuve", "0007_epreuve_epreuve_referen_cb6879_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="groupeparticipeaepreuve",
            index=models.Index(
                fields=["epreuve"], name="GroupeParti_epreuve_50d550_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membrecomite",
            index=models.Index(
                fields=["membre", "epreuve"], name="MembreComit_membre__c8d644_idx"
            ),
        ),
    ]
