# Generated by Django 5.0.3 on 2024-03-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuve', '0007_remove_userepreuve_fin_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='separateur_jeu_test',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='separateur_reponse_jeudetest',
            field=models.CharField(blank=True, null=True),
        ),
    ]
