# Generated by Django 5.0 on 2024-01-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epreuve",
            "0008_groupeparticipeaepreuve_groupeparti_epreuve_50d550_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="epreuve",
            name="date_debut",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="date_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
