# Generated by Django 5.0.3 on 2024-04-27 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0008_exercice_separateur_jeu_test_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="epreuve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercices",
                to="epreuve.epreuve",
            ),
        ),
        migrations.AlterField(
            model_name="userepreuve",
            name="epreuve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_entries",
                to="epreuve.epreuve",
            ),
        ),
        migrations.AlterField(
            model_name="userepreuve",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_epreuves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userexercice",
            name="exercice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_exercices",
                to="epreuve.exercice",
            ),
        ),
        migrations.AlterField(
            model_name="userexercice",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_exercices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
