# Generated by Django 5.0 on 2024-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0009_alter_epreuve_date_debut_alter_epreuve_date_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epreuve",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
