# Generated by Django 5.0.3 on 2025-03-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0009_alter_exercice_epreuve_alter_userepreuve_epreuve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userepreuve",
            name="anonymat",
            field=models.CharField(
                blank=True,
                help_text="Stocke les numéros d'anonymat des 3 participants séparés par '|'.",
                max_length=255,
                null=True,
            ),
        ),
    ]
