# Generated by Django 5.0 on 2024-01-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0010_alter_epreuve_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("bareme", models.IntegerField(null=True)),
                ("bonne_reponse", models.TextField(null=True)),
                (
                    "type_exercice",
                    models.CharField(
                        choices=[
                            ("programmation", "Programmation"),
                            ("qcm", "QCM"),
                            ("qroc", "QROC"),
                            ("qcs", "QCS"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "type_enonce",
                    models.CharField(
                        choices=[
                            ("text", "Texte Simple"),
                            ("latex", "LaTeX"),
                            ("code", "Code (python, ...)"),
                        ],
                        max_length=6,
                    ),
                ),
                ("enonce", models.TextField()),
                ("instance_probleme_prog_a_resoudre", models.TextField(null=True)),
                (
                    "instances_uniques_par_participant",
                    models.BooleanField(default=False),
                ),
                ("nombre_max_soumissions_solution", models.IntegerField(default=50)),
                ("nombre_max_soumissions_code", models.IntegerField(default=50)),
                ("code_a_soumettre", models.BooleanField(default=False)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
            ],
            options={
                "db_table": "Exercice",
                "indexes": [
                    models.Index(fields=["epreuve"], name="Exercice_epreuve_474577_idx")
                ],
            },
        ),
    ]
