# Generated by Django 5.0.3 on 2025-03-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0010_userepreuve_anonymat"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuve",
            name="annale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="epreuves_associees",
                to="epreuve.epreuve",
            ),
        ),
    ]
