# Generated by Django 5.1.7 on 2025-03-29 07:03

from django.db import migrations, models


def set_default_code_a_soumettre(apps, schema_editor):
    Exercice = apps.get_model("epreuve", "Exercice")
    Exercice.objects.filter(code_a_soumettre__isnull=True).update(code_a_soumettre="python")


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0011_epreuve_annale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="code_a_soumettre",
            field=models.CharField(
                choices=[
                    ("aucun", "Aucun code à soumettre"),
                    ("python", "Code Python à soumettre"),
                    ("autre", "Code dans un autre langage"),
                ],
                default="python",
                max_length=10,
                null=True,  # on laisse temporairement null pour permettre la migration
            ),
        ),
        migrations.RunPython(set_default_code_a_soumettre),
        migrations.AlterField(
            model_name="exercice",
            name="code_a_soumettre",
            field=models.CharField(
                choices=[
                    ("aucun", "Aucun code à soumettre"),
                    ("python", "Code Python à soumettre"),
                    ("autre", "Code dans un autre langage"),
                ],
                default="python",
                max_length=10,
                null=False,  # on retire null une fois toutes les lignes corrigées
            ),
        ),
    ]
