# Generated by Django 5.0 on 2024-01-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0012_userexercice_userepreuve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userepreuve",
            name="debut_epreuve",
        ),
        migrations.AddField(
            model_name="userepreuve",
            name="fin_epreuve",
            field=models.DateTimeField(null=True),
        ),
    ]
