# Generated by Django 5.1.8 on 2026-01-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0013_alter_exercice_code_a_soumettre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="code_a_soumettre",
            field=models.CharField(
                choices=[
                    ("aucun", "Aucun code à soumettre"),
                    ("python", "Code Python à soumettre"),
                    ("autre", "Code dans un autre langage"),
                ],
                default="python",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jeudetest",
            name="exercice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jeux_de_test",
                to="epreuve.exercice",
            ),
        ),
    ]
