# Generated by Django 5.0 on 2024-01-14 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0014_jeudetest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercice",
            old_name="instances_uniques_par_participant",
            new_name="avec_jeu_de_test",
        ),
        migrations.RemoveField(
            model_name="exercice",
            name="bonne_reponse",
        ),
        migrations.RemoveField(
            model_name="exercice",
            name="instance_probleme_prog_a_resoudre",
        ),
        migrations.AddField(
            model_name="exercice",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="duree",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="referent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epreuve_referent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
