# Generated by Django 5.0 on 2024-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epreuve",
            "0015_rename_instances_uniques_par_participant_exercice_avec_jeu_de_test_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercice",
            name="type_enonce",
        ),
        migrations.AddField(
            model_name="exercice",
            name="enonce_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercice",
            name="retour_en_direct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exercice",
            name="enonce",
            field=models.TextField(blank=True, null=True),
        ),
    ]
