# Generated by Django 5.0 on 2024-01-16 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0016_remove_exercice_type_enonce_exercice_enonce_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercice",
            name="type_exercice",
        ),
    ]
