# Generated by Django 5.0 on 2024-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0018_alter_exercice_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
