# Generated by Django 5.0.1 on 2024-01-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0019_alter_exercice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercice",
            name="type_exercice",
            field=models.CharField(
                choices=[
                    ("programmation", "Programmation"),
                    ("qcm", "QCM"),
                    ("qroc", "QROC"),
                    ("qcs", "QCS"),
                ],
                default="programmation",
                max_length=14,
            ),
        ),
    ]
