# Generated by Django 5.0.1 on 2024-01-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0020_exercice_type_exercice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userexercice",
            name="solution_instance_correction",
        ),
        migrations.AlterField(
            model_name="userexercice",
            name="instance_participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="epreuve.jeudetest",
            ),
        ),
    ]
