# Generated by Django 5.0.1 on 2024-01-19 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0021_remove_userexercice_solution_instance_correction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userexercice",
            old_name="instance_participant",
            new_name="jeu_de_test",
        ),
    ]
