# Generated by Django 5.0.1 on 2024-01-19 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0022_rename_instance_participant_userexercice_jeu_de_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userexercice",
            old_name="nombre_soumissions_code",
            new_name="nb_solutions_jeu_de_test",
        ),
        migrations.RenameField(
            model_name="userexercice",
            old_name="nombre_soumissions_solution_instance",
            new_name="nb_soumissions_code",
        ),
    ]
