# Generated by Django 5.0.1 on 2024-01-20 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "epreuve",
            "0023_rename_nombre_soumissions_code_userexercice_nb_solutions_jeu_de_test_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercice",
            old_name="nombre_max_soumissions_code",
            new_name="nombre_max_soumissions",
        ),
        migrations.RemoveField(
            model_name="exercice",
            name="nombre_max_soumissions_solution",
        ),
    ]
