# Generated by Django 5.0.1 on 2024-01-20 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "epreuve",
            "0024_rename_nombre_max_soumissions_code_exercice_nombre_max_soumissions_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userexercice",
            old_name="nb_solutions_jeu_de_test",
            new_name="nb_soumissions",
        ),
        migrations.RemoveField(
            model_name="userexercice",
            name="nb_soumissions_code",
        ),
    ]
