# Generated by Django 5.0.1 on 2024-01-22 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "epreuve",
            "0025_rename_nb_solutions_jeu_de_test_userexercice_nb_soumissions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epreuve",
            name="description",
        ),
    ]
