# Generated by Django 5.0.1 on 2024-01-23 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0026_remove_epreuve_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercice",
            name="description",
        ),
    ]
