# Generated by Django 5.0.1 on 2024-01-24 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0027_remove_exercice_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exercice",
            name="numero",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="membrecomite",
            unique_together={("epreuve", "membre")},
        ),
    ]
