# Generated by Django 5.0.1 on 2024-01-24 23:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("epreuve", "0028_exercice_numero_alter_membrecomite_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupecreepar",
            unique_together={("groupe", "createur")},
        ),
        migrations.AlterUniqueTogether(
            name="groupeparticipeaepreuve",
            unique_together={("groupe", "epreuve")},
        ),
        migrations.AlterUniqueTogether(
            name="userepreuve",
            unique_together={("participant", "epreuve")},
        ),
    ]
