# Generated by Django 5.0.1 on 2024-01-25 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0029_alter_groupecreepar_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jeudetest",
            name="exercice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="epreuve.exercice"
            ),
        ),
    ]
