# Generated by Django 5.0.1 on 2024-02-18 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("epreuve", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(blank=True, max_length=100, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("token_est_utilise", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Inscripteur",
            },
        ),
        migrations.CreateModel(
            name="InscriptionDomaine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domaine", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Inscription_domaine",
            },
        ),
        migrations.CreateModel(
            name="CompteurParticipantsAssocies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nb_participants_associes", models.IntegerField(default=0)),
                (
                    "organisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="User_CompteurParticipantsAssocies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "compteur de participants associes à organisateur",
                "verbose_name_plural": "compteurs de participants associes à organisateur",
                "db_table": "Organisateur_CompteurParticipant",
            },
        ),
        migrations.CreateModel(
            name="GroupeParticipeAEpreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
            ],
            options={
                "db_table": "GroupeParticipeAEpreuve",
            },
        ),
    ]
