# Generated by Django 5.0.1 on 2024-02-17 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("epreuve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(blank=True, max_length=100, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("token_est_utilise", models.BooleanField(default=False)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
            ],
            options={
                "db_table": "Inscripteur",
            },
        ),
        migrations.CreateModel(
            name="GroupeParticipeAEpreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            options={
                "db_table": "GroupeParticipeAEpreuve",
                "indexes": [
                    models.Index(
                        fields=["groupe", "epreuve"],
                        name="GroupeParti_groupe__c70cd8_idx",
                    ),
                    models.Index(
                        fields=["epreuve"], name="GroupeParti_epreuve_50d550_idx"
                    ),
                ],
                "unique_together": {("groupe", "epreuve")},
            },
        ),
        migrations.CreateModel(
            name="Inscription_domaine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domaine", models.CharField(max_length=100)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
            ],
            options={
                "db_table": "Inscription_domaine",
                "indexes": [
                    models.Index(
                        fields=["epreuve"], name="Inscription_epreuve_87c641_idx"
                    )
                ],
            },
        ),
    ]
