# Generated by Django 5.0.1 on 2024-02-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0002_initial"),
        ("inscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripteur",
            name="epreuve",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="epreuve.epreuve",
            ),
            preserve_default=False,
        ),
    ]
