# Generated by Django 5.0.1 on 2024-02-18 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("epreuve", "0002_initial"),
        ("inscription", "0001_initial"),
        ("intranet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupeparticipeaepreuve",
            name="groupe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="intranet.groupeparticipant",
            ),
        ),
        migrations.AddField(
            model_name="inscripteur",
            name="epreuve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="epreuve.epreuve"
            ),
        ),
        migrations.AddField(
            model_name="inscriptiondomaine",
            name="epreuve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="epreuve.epreuve"
            ),
        ),
        migrations.AddIndex(
            model_name="compteurparticipantsassocies",
            index=models.Index(
                fields=["organisateur"], name="Organisateu_organis_6a7f84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupeparticipeaepreuve",
            index=models.Index(
                fields=["groupe", "epreuve"], name="GroupeParti_groupe__c70cd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupeparticipeaepreuve",
            index=models.Index(
                fields=["epreuve"], name="GroupeParti_epreuve_50d550_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupeparticipeaepreuve",
            unique_together={("groupe", "epreuve")},
        ),
        migrations.AddIndex(
            model_name="inscriptiondomaine",
            index=models.Index(
                fields=["epreuve"], name="Inscription_epreuve_87c641_idx"
            ),
        ),
    ]
