# Generated by Django 5.0.1 on 2024-02-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0002_initial"),
        ("inscription", "0002_initial"),
        ("intranet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscripteurExterne",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "InscripteurExterne",
            },
        ),
        migrations.CreateModel(
            name="InscriptionExterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=100, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("token_est_utilise", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "InscriptionExterne",
            },
        ),
        migrations.RemoveField(
            model_name="inscripteur",
            name="epreuve",
        ),
        migrations.RemoveIndex(
            model_name="groupeparticipeaepreuve",
            name="GroupeParti_groupe__c70cd8_idx",
        ),
        migrations.AddIndex(
            model_name="groupeparticipeaepreuve",
            index=models.Index(
                fields=["groupe"], name="GroupeParti_groupe__ad4326_idx"
            ),
        ),
        migrations.AddField(
            model_name="inscriptionexterne",
            name="epreuve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="epreuve.epreuve"
            ),
        ),
        migrations.AddField(
            model_name="inscriptionexterne",
            name="inscripteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inscription.inscripteurexterne",
            ),
        ),
    ]
