# Generated by Django 5.0.1 on 2024-02-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0003_delete_inscription_domaine"),
        ("inscription", "0002_inscripteur_epreuve"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscription_domaine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domaine", models.CharField(max_length=100)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epreuve.epreuve",
                    ),
                ),
            ],
            options={
                "db_table": "Inscription_domaine",
                "indexes": [
                    models.Index(
                        fields=["epreuve"], name="Inscription_epreuve_87c641_idx"
                    )
                ],
            },
        ),
    ]
