# Generated by Django 5.0.1 on 2024-02-19 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0003_inscripteurexterne_inscriptionexterne_and_more"),
        ("intranet", "0002_alter_groupeparticipant_inscripteur"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inscripteur",
        ),
    ]
