# Generated by Django 5.0.2 on 2024-02-22 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0005_rename_code_unique_epreuve_code"),
        ("inscription", "0005_alter_inscriptionexterne_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="compteurparticipantsassocies",
            name="Organisateu_organis_6a7f84_idx",
        ),
        migrations.RemoveField(
            model_name="compteurparticipantsassocies",
            name="id",
        ),
        migrations.AlterField(
            model_name="compteurparticipantsassocies",
            name="organisateur",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="compteur_participants_associes",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="inscriptionexterne",
            index=models.Index(
                fields=["inscripteur"], name="Inscription_inscrip_33dfd0_idx"
            ),
        ),
    ]
