# Generated by Django 5.0.2 on 2024-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inscription",
            "0006_remove_compteurparticipantsassocies_organisateu_organis_6a7f84_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionexterne",
            name="inscription_validee",
            field=models.BooleanField(default=False),
        ),
    ]
