# Generated by Django 5.0.2 on 2024-02-28 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0007_inscriptionexterne_inscription_validee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscriptionexterne",
            name="inscription_validee",
        ),
    ]
