# Generated by Django 5.1.8 on 2026-01-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0014_alter_exercice_code_a_soumettre_and_more"),
        ("inscription", "0009_inscriptionexterne_nombre_participants_demandes"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionOlympiades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_uai",
                    models.CharField(
                        db_index=True,
                        help_text="Code UAI de l'établissement (ex: 0781234A).",
                        max_length=16,
                    ),
                ),
                (
                    "email_enseignant",
                    models.EmailField(
                        help_text="Email académique du professeur (contact).",
                        max_length=100,
                    ),
                ),
                ("nom_etablissement", models.CharField(blank=True, max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("email_etablissement", models.EmailField(blank=True, max_length=100)),
                (
                    "nom_enseignant",
                    models.CharField(
                        blank=True,
                        help_text="Nom (ou nom+prénom) de l'enseignant de contact.",
                        max_length=100,
                    ),
                ),
                (
                    "nb_candidats_ecrit",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de candidats pour l'épreuve écrite (individuelle).",
                    ),
                ),
                (
                    "nb_equipes_pratique",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre d'équipes pour l'épreuve pratique (1 à 3 élèves).",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_olympiades",
                        to="epreuve.epreuve",
                    ),
                ),
            ],
            options={
                "db_table": "InscriptionOlympiades",
                "indexes": [
                    models.Index(
                        fields=["epreuve", "code_uai"],
                        name="Inscription_epreuve_8f1e28_idx",
                    ),
                    models.Index(
                        fields=["code_uai"], name="Inscription_code_ua_3d0e7f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("epreuve", "code_uai", "email_enseignant"),
                        name="unique_epreuve_uai_email_enseignant",
                    )
                ],
            },
        ),
    ]
