# Generated by Django 5.1.8 on 2026-01-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0010_inscriptionolympiades"),
        ("intranet", "0003_remove_groupeparticipant_inscripteur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionOlympiadesGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_groupe",
                    models.CharField(
                        choices=[("olympiades", "Olympiades"), ("annales", "Annales")],
                        max_length=16,
                    ),
                ),
                ("numero", models.PositiveIntegerField(default=1)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_olympiades_associees",
                        to="intranet.groupeparticipant",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_associes",
                        to="inscription.inscriptionolympiades",
                    ),
                ),
            ],
            options={
                "db_table": "InscriptionOlympiadesGroupe",
                "indexes": [
                    models.Index(
                        fields=["inscription", "type_groupe"],
                        name="Inscription_inscrip_ccc80f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inscription", "type_groupe", "numero"),
                        name="unique_inscription_type_numero",
                    ),
                    models.UniqueConstraint(
                        fields=("inscription", "groupe"),
                        name="unique_inscription_groupe",
                    ),
                ],
            },
        ),
    ]
