# Generated by Django 5.1.8 on 2026-01-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0014_alter_exercice_code_a_soumettre_and_more"),
        ("inscription", "0011_inscriptionolympiadesgroupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_uai",
                    models.CharField(
                        db_index=True,
                        help_text="Code UAI (ex: 0781234A).",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(blank=True, default="", max_length=100)),
                ("commune", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(blank=True, default="", max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Etablissement",
            },
        ),
        migrations.RemoveConstraint(
            model_name="inscriptionolympiades",
            name="unique_epreuve_uai_email_enseignant",
        ),
        migrations.AddIndex(
            model_name="etablissement",
            index=models.Index(
                fields=["code_uai"], name="Etablisseme_code_ua_1b3800_idx"
            ),
        ),
        migrations.AddField(
            model_name="inscriptionolympiades",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions_olympiades",
                to="inscription.etablissement",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscriptionolympiades",
            constraint=models.UniqueConstraint(
                fields=("epreuve", "etablissement", "email_enseignant"),
                name="unique_epreuve_etablissement_email_enseignant",
            ),
        ),
    ]
