# Generated by Django 5.1.8 on 2026-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0012_etablissement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscriptionolympiades",
            name="commune",
        ),
        migrations.RemoveField(
            model_name="inscriptionolympiades",
            name="email_etablissement",
        ),
        migrations.RemoveField(
            model_name="inscriptionolympiades",
            name="nom_etablissement",
        ),
    ]
