# Generated by Django 5.1.8 on 2026-01-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0013_remove_inscriptionolympiades_commune_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionolympiades",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions_olympiades",
                to="inscription.etablissement",
            ),
        ),
    ]
