# Generated by Django 5.1.8 on 2026-01-21 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0014_alter_exercice_code_a_soumettre_and_more"),
        ("inscription", "0014_alter_inscriptionolympiades_etablissement"),
        ("intranet", "0003_remove_groupeparticipant_inscripteur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionAnnales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enseignant", models.EmailField(max_length=100)),
                (
                    "nom_enseignant",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_annales",
                        to="epreuve.epreuve",
                    ),
                ),
            ],
            options={
                "db_table": "InscriptionAnnales",
            },
        ),
        migrations.CreateModel(
            name="InscriptionAnnalesGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(default=1)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_annales_associees",
                        to="intranet.groupeparticipant",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_associes",
                        to="inscription.inscriptionannales",
                    ),
                ),
            ],
            options={
                "db_table": "InscriptionAnnalesGroupe",
            },
        ),
        migrations.AddIndex(
            model_name="inscriptionannales",
            index=models.Index(
                fields=["epreuve", "email_enseignant"],
                name="Inscription_epreuve_b26e47_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscriptionannales",
            constraint=models.UniqueConstraint(
                fields=("epreuve", "email_enseignant"),
                name="unique_epreuve_email_annales",
            ),
        ),
        migrations.AddIndex(
            model_name="inscriptionannalesgroupe",
            index=models.Index(
                fields=["inscription"], name="Inscription_inscrip_6d4754_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscriptionannalesgroupe",
            constraint=models.UniqueConstraint(
                fields=("inscription", "numero"),
                name="unique_inscription_annales_numero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscriptionannalesgroupe",
            constraint=models.UniqueConstraint(
                fields=("inscription", "groupe"),
                name="unique_inscription_annales_groupe",
            ),
        ),
    ]
