# Generated by Django 5.1.8 on 2026-01-21 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0015_inscriptionannales_inscriptionannalesgroupe_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InscriptionAnnalesGroupe",
        ),
    ]
