# Generated by Django 5.1.8 on 2026-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0016_delete_inscriptionannalesgroupe"),
        ("intranet", "0003_remove_groupeparticipant_inscripteur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionannales",
            name="groupes_associes",
            field=models.ManyToManyField(
                blank=True,
                related_name="inscriptions_annales_associees",
                to="intranet.groupeparticipant",
            ),
        ),
    ]
