# Generated by Django 5.1.8 on 2026-01-25 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epreuve", "0014_alter_exercice_code_a_soumettre_and_more"),
        ("inscription", "0017_inscriptionannales_groupes_associes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptiondomaine",
            name="epreuve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domaines_inscription",
                to="epreuve.epreuve",
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionexterne",
            name="epreuve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions_externes",
                to="epreuve.epreuve",
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionexterne",
            name="inscripteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions_externes",
                to="inscription.inscripteurexterne",
            ),
        ),
        migrations.CreateModel(
            name="AnonymatEpreuveEcrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        help_text="Numéro 0..999 correspondant aux 3 chiffres après l'UAI.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymats_ecrits",
                        to="epreuve.epreuve",
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anonymats_ecrits",
                        to="inscription.etablissement",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymats_ecrits",
                        to="inscription.inscriptionolympiades",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["epreuve", "etablissement", "actif"],
                        name="inscription_epreuve_0b0126_idx",
                    ),
                    models.Index(
                        fields=["inscription", "actif"],
                        name="inscription_inscrip_543860_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("actif", True)),
                        fields=("epreuve", "etablissement", "numero"),
                        name="uniq_anonymat_actif_par_epreuve_etab_numero",
                    )
                ],
            },
        ),
    ]
